name: Atualizar YAML

on:
  push:
    branches:
      - main

jobs:
  update_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Verificar estrutura de arquivos (debug)
        run: |
          echo "Diretório atual: $(pwd)"
          ls -lah
          ls -lah atualizar_yaml.py || echo "Script NÃO encontrado!"

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pandas

      - name: Rodar script Python
        run: python atualizar_yaml.py

      - name: Commit e Push se houver mudanças
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add projetos.yml
          git diff --quiet || (
            git commit -m "Atualiza projetos.yml com dados do CSV"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          )
